language: python
sudo: false
services:
  - postgresql
  - mysql
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO="Django>=1.8,<1.9" DB=sqlite
  - DJANGO="Django>=1.8,<1.9" DB=postgres
  - DJANGO="Django>=1.8,<1.9" DB=mysql
  - DJANGO="Django>=1.9,<1.10" DB=sqlite
  - DJANGO="Django>=1.9,<1.10" DB=postgres
  - DJANGO="Django>=1.9,<1.10" DB=mysql

install:
  - if [[ $DB == mysql ]]; then pip install -qU mysqlclient; fi
  - if [[ $DB == postgres ]]; then pip install -qU psycopg2; fi
  - pip install -qU $DJANGO
  - CFLAGS="-O0" pip install -qU -r test/requirements.txt

before_script:
  - mysql -e 'create database pybbm;'
  - psql -c 'create database pybbm;' -U postgres

script:
  - python setup.py test
